### ISSUE TITLE
pip install deezymatch

### ISSUE THREAD

**Issue by benwatsoncpa** [Living-with-machines/DeezyMatch#137]
error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\benwa\AppData\Local\Temp\pip-install-4j12lxj3\deezymatch_6326d6e43bb54df3be73ff085400a9bc\setup.py", line 11, in <module>
          long_description = open('README.md').read(),
        File "C:\Users\benwa\anaconda3\envs\py39deezy\lib\encodings\cp1252.py", line 23, in decode
          return codecs.charmap_decode(input,self.errors,decoding_table)[0]
      UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 7858: character maps to <undefined>
      [end of output]

**Comment by benwatsoncpa** [comment]
can be fixed by changing line 11 of setup.py to  `long_description = open('README.md', encoding='utf8').read(),`
